replicaCount: 1
namespaceOverride: ""
nameOverride: ""
fullnameOverride: ""

# this represents the kube-ovn parameters
network:
  SubNetName: ""
  podEgressRate: "20"
  podIngressRate: "20"

service:
  type: NodePort
  port: 80
  nodePort: 31000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: "2Gi"
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: "2Gi"

nodeSelector: {}
