apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "360video-transcoder.fullname" . }}
  labels:
    {{- include "360video-transcoder.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "360video-transcoder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        ovn.kubernetes.io/ingress_rate: {{ .Values.network.podIngressRate }}
        ovn.kubernetes.io/egress_rate: {{ .Values.network.podEgressRate }}
      labels:
        {{- include "360video-transcoder.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: nginx:1.14.2
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: ephemeral
              mountPath: "/tmp"
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: ephemeral
          emptyDir: {}
